[[redirects]]
from = "https://storage-remzi.netlify.app/*"
to = "https://storage.remzi.info/:splat"
status = 301
force = true

# Default favicon redirect
[[redirects]]
from = "/favicon.ico"
to = "/images/logo.png"
status = 301

# Redirects
[[redirects]]
from = "/assets/images/logo.png"
to = "/images/logo.png"
status = 301

[[redirects]]
from = "/assets/docs/Curriculum-vitae-R.Cavdar.pdf"
to = "/docs/Curriculum-vitae-R.Cavdar.pdf"
status = 301

[[redirects]]
from = "/assets/docs/Onderzoeksverslag-van-R.Cavdar-20-01-2023.pdf"
to = "/docs/Onderzoeksverslag-van-R.Cavdar-20-01-2023.pdf"
status = 301

[[redirects]]
from = "/assets/docs/The-future-is-modular-R.Cavdar-06-11-2023.pdf"
to = "/docs/The-future-is-modular-R.Cavdar-06-11-2023.pdf"
status = 301